package com.test.model;

public class MerchUserDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.id
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.user_roler
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private Integer userRoler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.merch_id
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private Integer merchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.login_name
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.true_name
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private String trueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.password
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.telephone
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.mobile
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.email
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.address
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.status
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.last_login
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private String lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.login_error_date
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private String loginErrorDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.error_count
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private Integer errorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.branchno
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private String branchno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.head_index
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private Integer headIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_user.open_id
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    private String openId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.id
     *
     * @return the value of merch_user.id
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.id
     *
     * @param id the value for merch_user.id
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.user_roler
     *
     * @return the value of merch_user.user_roler
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public Integer getUserRoler() {
        return userRoler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.user_roler
     *
     * @param userRoler the value for merch_user.user_roler
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setUserRoler(Integer userRoler) {
        this.userRoler = userRoler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.merch_id
     *
     * @return the value of merch_user.merch_id
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public Integer getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.merch_id
     *
     * @param merchId the value for merch_user.merch_id
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setMerchId(Integer merchId) {
        this.merchId = merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.login_name
     *
     * @return the value of merch_user.login_name
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.login_name
     *
     * @param loginName the value for merch_user.login_name
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.true_name
     *
     * @return the value of merch_user.true_name
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.true_name
     *
     * @param trueName the value for merch_user.true_name
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName == null ? null : trueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.password
     *
     * @return the value of merch_user.password
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.password
     *
     * @param password the value for merch_user.password
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.telephone
     *
     * @return the value of merch_user.telephone
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.telephone
     *
     * @param telephone the value for merch_user.telephone
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.mobile
     *
     * @return the value of merch_user.mobile
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.mobile
     *
     * @param mobile the value for merch_user.mobile
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.email
     *
     * @return the value of merch_user.email
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.email
     *
     * @param email the value for merch_user.email
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.address
     *
     * @return the value of merch_user.address
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.address
     *
     * @param address the value for merch_user.address
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.status
     *
     * @return the value of merch_user.status
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.status
     *
     * @param status the value for merch_user.status
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.last_login
     *
     * @return the value of merch_user.last_login
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public String getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.last_login
     *
     * @param lastLogin the value for merch_user.last_login
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setLastLogin(String lastLogin) {
        this.lastLogin = lastLogin == null ? null : lastLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.login_error_date
     *
     * @return the value of merch_user.login_error_date
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public String getLoginErrorDate() {
        return loginErrorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.login_error_date
     *
     * @param loginErrorDate the value for merch_user.login_error_date
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setLoginErrorDate(String loginErrorDate) {
        this.loginErrorDate = loginErrorDate == null ? null : loginErrorDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.error_count
     *
     * @return the value of merch_user.error_count
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public Integer getErrorCount() {
        return errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.error_count
     *
     * @param errorCount the value for merch_user.error_count
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setErrorCount(Integer errorCount) {
        this.errorCount = errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.branchno
     *
     * @return the value of merch_user.branchno
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public String getBranchno() {
        return branchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.branchno
     *
     * @param branchno the value for merch_user.branchno
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setBranchno(String branchno) {
        this.branchno = branchno == null ? null : branchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.head_index
     *
     * @return the value of merch_user.head_index
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public Integer getHeadIndex() {
        return headIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.head_index
     *
     * @param headIndex the value for merch_user.head_index
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setHeadIndex(Integer headIndex) {
        this.headIndex = headIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merch_user.open_id
     *
     * @return the value of merch_user.open_id
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merch_user.open_id
     *
     * @param openId the value for merch_user.open_id
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }
}