/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

/**
 * @Copyright 2016 www.bestpay.io Inc. All rights reserved.
 */

package io.bestpay.framework.resource;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum CardType {
  UNKNOW, DEBIT, CREDIT, PREPAYMENT_CARD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CardType\",\"namespace\":\"io.bestpay.framework.resource\",\"symbols\":[\"UNKNOW\",\"DEBIT\",\"CREDIT\",\"PREPAYMENT_CARD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /**   */
  public static CardType valueOf(int ordinal) {
	  CardType[] values = CardType.values();
	  for (CardType s : values) {
		  if (s.ordinal() == ordinal) {
			  return s;
		  }
	  }
	  throw new org.apache.avro.AvroRuntimeException("Bad ordinal");
  }  
}
