/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

/**
 * @Copyright 2016 www.bestpay.io Inc. All rights reserved.
 */

package io.bestpay.framework.resource;

import org.apache.avro.specific.SpecificData;

import org.codehaus.jackson.map.annotate.JsonSerialize.Inclusion;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@SuppressWarnings("all")
/** 行政区管理 */
@javax.xml.bind.annotation.XmlRootElement
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
@javax.xml.bind.annotation.XmlType(name="Region", namespace="io.bestpay.framework.resource")
@org.apache.avro.specific.AvroGenerated
public class Region extends io.bestpay.framework.base.SpecificRecordBase implements io.bestpay.framework.base.SpecificRecord {
  private static final long serialVersionUID = -8407259326372580851L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Region\",\"namespace\":\"io.bestpay.framework.resource\",\"doc\":\"行政区管理\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"主键\"},{\"name\":\"region_code\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"代码\",\"default\":\"\"},{\"name\":\"region_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"名称\",\"default\":\"\"},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"备注\",\"default\":\"\"}],\"aliases\":[\"Region\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** 主键 */
  @javax.xml.bind.annotation.XmlElement(name="id")
  private java.lang.String id;
  /** 代码 */
  @javax.xml.bind.annotation.XmlElement(name="region_code")
  private java.lang.String region_code;
  /** 名称 */
  @javax.xml.bind.annotation.XmlElement(name="region_name")
  private java.lang.String region_name;
  /** 备注 */
  @javax.xml.bind.annotation.XmlElement(name="description")
  private java.lang.String description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Region() {}

  /**
   * All-args constructor.
   * @param id 主键
   * @param region_code 代码
   * @param region_name 名称
   * @param description 备注
   */
  public Region(java.lang.String id, java.lang.String region_code, java.lang.String region_name, java.lang.String description) {
    this.id = id;
    this.region_code = region_code;
    this.region_name = region_name;
    this.description = description;
  }

  @com.fasterxml.jackson.annotation.JsonIgnore
  @org.codehaus.jackson.annotate.JsonIgnore
  @javax.xml.bind.annotation.XmlTransient
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return region_code;
    case 2: return region_name;
    case 3: return description;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: region_code = (java.lang.String)value$; break;
    case 2: region_name = (java.lang.String)value$; break;
    case 3: description = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return 主键
   */
  @com.fasterxml.jackson.annotation.JsonGetter("id")
  @org.codehaus.jackson.annotate.JsonProperty("id")   
  @com.fasterxml.jackson.annotation.JsonInclude(Include.NON_NULL)
  @org.codehaus.jackson.map.annotate.JsonSerialize(include=Inclusion.NON_NULL)  
  @javax.xml.bind.annotation.XmlTransient
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * 主键
   * @param value the value to set.
   */
  protected void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'region_code' field.
   * @return 代码
   */
  @com.fasterxml.jackson.annotation.JsonGetter("region_code")
  @org.codehaus.jackson.annotate.JsonProperty("region_code")   
  @com.fasterxml.jackson.annotation.JsonInclude(Include.NON_NULL)
  @org.codehaus.jackson.map.annotate.JsonSerialize(include=Inclusion.NON_NULL)  
  @javax.xml.bind.annotation.XmlTransient
  public java.lang.String getRegionCode() {
    return region_code;
  }

  /**
   * Sets the value of the 'region_code' field.
   * 代码
   * @param value the value to set.
   */
  protected void setRegionCode(java.lang.String value) {
    this.region_code = value;
  }

  /**
   * Gets the value of the 'region_name' field.
   * @return 名称
   */
  @com.fasterxml.jackson.annotation.JsonGetter("region_name")
  @org.codehaus.jackson.annotate.JsonProperty("region_name")   
  @com.fasterxml.jackson.annotation.JsonInclude(Include.NON_NULL)
  @org.codehaus.jackson.map.annotate.JsonSerialize(include=Inclusion.NON_NULL)  
  @javax.xml.bind.annotation.XmlTransient
  public java.lang.String getRegionName() {
    return region_name;
  }

  /**
   * Sets the value of the 'region_name' field.
   * 名称
   * @param value the value to set.
   */
  protected void setRegionName(java.lang.String value) {
    this.region_name = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return 备注
   */
  @com.fasterxml.jackson.annotation.JsonGetter("description")
  @org.codehaus.jackson.annotate.JsonProperty("description")   
  @com.fasterxml.jackson.annotation.JsonInclude(Include.NON_NULL)
  @org.codehaus.jackson.map.annotate.JsonSerialize(include=Inclusion.NON_NULL)  
  @javax.xml.bind.annotation.XmlTransient
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * 备注
   * @param value the value to set.
   */
  protected void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Creates a new Region RecordBuilder.
   * @return A new Region RecordBuilder
   */
  public static io.bestpay.framework.resource.Region.Builder newBuilder() {
    return new io.bestpay.framework.resource.Region.Builder();
  }

  /**
   * Creates a new Region RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Region RecordBuilder
   */
  public static io.bestpay.framework.resource.Region.Builder newBuilder(io.bestpay.framework.resource.Region.Builder other) {
    return new io.bestpay.framework.resource.Region.Builder(other);
  }

  /**
   * Creates a new Region RecordBuilder by copying an existing Region instance.
   * @param other The existing instance to copy.
   * @return A new Region RecordBuilder
   */
  public static io.bestpay.framework.resource.Region.Builder newBuilder(io.bestpay.framework.resource.Region other) {
    return new io.bestpay.framework.resource.Region.Builder(other);
  }

  /**
   * RecordBuilder for Region instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Region>
    implements org.apache.avro.data.RecordBuilder<Region> {

    /** 主键 */
    private java.lang.String id;
    /** 代码 */
    private java.lang.String region_code;
    /** 名称 */
    private java.lang.String region_name;
    /** 备注 */
    private java.lang.String description;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.bestpay.framework.resource.Region.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.region_code)) {
        this.region_code = data().deepCopy(fields()[1].schema(), other.region_code);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.region_name)) {
        this.region_name = data().deepCopy(fields()[2].schema(), other.region_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Region instance
     * @param other The existing instance to copy.
     */
    private Builder(io.bestpay.framework.resource.Region other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.region_code)) {
        this.region_code = data().deepCopy(fields()[1].schema(), other.region_code);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.region_name)) {
        this.region_name = data().deepCopy(fields()[2].schema(), other.region_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * 主键
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * 主键
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.bestpay.framework.resource.Region.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * 主键
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * 主键
      * @return This builder.
      */
    public io.bestpay.framework.resource.Region.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'region_code' field.
      * 代码
      * @return The value.
      */
    public java.lang.String getRegionCode() {
      return region_code;
    }

    /**
      * Sets the value of the 'region_code' field.
      * 代码
      * @param value The value of 'region_code'.
      * @return This builder.
      */
    public io.bestpay.framework.resource.Region.Builder setRegionCode(java.lang.String value) {
      validate(fields()[1], value);
      this.region_code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'region_code' field has been set.
      * 代码
      * @return True if the 'region_code' field has been set, false otherwise.
      */
    public boolean hasRegionCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'region_code' field.
      * 代码
      * @return This builder.
      */
    public io.bestpay.framework.resource.Region.Builder clearRegionCode() {
      region_code = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'region_name' field.
      * 名称
      * @return The value.
      */
    public java.lang.String getRegionName() {
      return region_name;
    }

    /**
      * Sets the value of the 'region_name' field.
      * 名称
      * @param value The value of 'region_name'.
      * @return This builder.
      */
    public io.bestpay.framework.resource.Region.Builder setRegionName(java.lang.String value) {
      validate(fields()[2], value);
      this.region_name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'region_name' field has been set.
      * 名称
      * @return True if the 'region_name' field has been set, false otherwise.
      */
    public boolean hasRegionName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'region_name' field.
      * 名称
      * @return This builder.
      */
    public io.bestpay.framework.resource.Region.Builder clearRegionName() {
      region_name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * 备注
      * @return The value.
      */
    public java.lang.String getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * 备注
      * @param value The value of 'description'.
      * @return This builder.
      */
    public io.bestpay.framework.resource.Region.Builder setDescription(java.lang.String value) {
      validate(fields()[3], value);
      this.description = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * 备注
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'description' field.
      * 备注
      * @return This builder.
      */
    public io.bestpay.framework.resource.Region.Builder clearDescription() {
      description = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public Region build() {
      try {
        Region record = new Region();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.region_code = fieldSetFlags()[1] ? this.region_code : (java.lang.String) defaultValue(fields()[1]);
        record.region_name = fieldSetFlags()[2] ? this.region_name : (java.lang.String) defaultValue(fields()[2]);
        record.description = fieldSetFlags()[3] ? this.description : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
