/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

/**
 * @Copyright 2016 www.bestpay.io Inc. All rights reserved.
 */

package io.bestpay.framework.resource;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ResourceType {
  APPLICATION, MODULE, VIEW, RESOURCE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ResourceType\",\"namespace\":\"io.bestpay.framework.resource\",\"symbols\":[\"APPLICATION\",\"MODULE\",\"VIEW\",\"RESOURCE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /**   */
  public static ResourceType valueOf(int ordinal) {
	  ResourceType[] values = ResourceType.values();
	  for (ResourceType s : values) {
		  if (s.ordinal() == ordinal) {
			  return s;
		  }
	  }
	  throw new org.apache.avro.AvroRuntimeException("Bad ordinal");
  }  
}
