package com.alycloud.modules.entity;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(value=Include.NON_NULL)
public class ReceiveDetailInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.id
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.merchno
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private String merchno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.merch_name
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private String merchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.agentno
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private String agentno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.agent_name
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private String agentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.branchno
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private String branchno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.branch_name
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private String branchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.orderno
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private String orderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.channel_orderno
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private String channelOrderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.amount
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.channel_fee
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private BigDecimal channelFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.branch_fee
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private BigDecimal branchFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.status
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.descr
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private String descr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.id_card
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fast_trans.settle_time
     *
     * @mbg.generated Mon Oct 23 11:08:10 GMT+08:00 2017
     */
    private String addTime;
    
    /**
     * 额外新增字段   存储当前列表收款总金额
     */
    private BigDecimal receiveTotal;
    
    /**
     * 支付方式
     */
    private String payType;
    
    /**
     * 收款手续费
     */
    private BigDecimal merchFee;
    
    /**
     * 提现费
     */
    private BigDecimal fee;
    
    /**
     * 手续费
     */
    private BigDecimal receiveFee;
    
    /**
     * 手续费率
     */
    private BigDecimal rate;
    
    /**
     * 结算卡号
     */
    private String settleCard;
    
    /**
     * 结算卡所属银行
     */
    private String bankName;
    
    /**
     * 可结算的金额
     */
    private BigDecimal settleAmount;
}