package com.alycloud.modules.entity;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(value=Include.NON_NULL)
public class WithdrawalDetailInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.id
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.trans_date
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String transDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.trans_time
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String transTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.branchno
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String branchno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.branch_name
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String branchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.agentno
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String agentno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.agent_name
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String agentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.merchno
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String merchno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.merch_name
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String merchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.cardno
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String cardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.trans_type
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private Integer transType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.amount
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.traceno
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String traceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.status
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.login_name
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.amount_before
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private BigDecimal amountBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.amount_after
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private BigDecimal amountAfter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.trans_amount
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private BigDecimal transAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.trans_fee
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private BigDecimal transFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.type_code
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.trans_refno
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String transRefno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.add_time
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.remark
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.pay_status
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private Integer payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.pay_msg
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String payMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.pay_type
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.batchno
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String batchno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.address
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.accountno
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String accountno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.account_name
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.bankno
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String bankno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.bank_name
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.process_time
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String processTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.df_type
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private Integer dfType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.mobile
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.bank_type
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String bankType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.channel_merchno
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private String channelMerchno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merch_virtual_trans.payment_type
     *
     * @mbg.generated Mon Oct 23 17:11:45 GMT+08:00 2017
     */
    private Integer paymentType;
    
    /**
     * 额外新增字段   存储当前列表提现金额
     */
    private BigDecimal withdrawalTotal;
    
    /**
     * 提现费
     */
    private BigDecimal fee;
    
    /**
     * 手续费
     */
    private BigDecimal withdrawFee;
    
    /**
     * 手续费率
     */
    private BigDecimal rate;
    
    /**
     * 结算卡号
     */
    private String settleCard;
    
    /**
     * 可结算的金额
     */
    private BigDecimal settleAmount;
}