/**
 * Autogenerated by bestpay-maven-plugin
 * DO NOT EDIT DIRECTLY
 *
 * @Copyright 2017 www.bestpay.io Inc. All rights reserved.
 * @Copyright 2017 www.bestpay.io Inc. All rights reserved.
 * @Copyright 2017 www.bestpay.io Inc. All rights reserved.
 * @Copyright 2017 www.bestpay.io Inc. All rights reserved.
 * @Copyright 2017 www.bestpay.io Inc. All rights reserved.
 * @Copyright 2017 www.bestpay.io Inc. All rights reserved.
 */

/**
 * @Copyright 2017 www.bestpay.io Inc. All rights reserved.
 */

package org.xiajinsuo.epay.exception;

@SuppressWarnings("all")
@javax.xml.bind.annotation.XmlRootElement
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
@javax.xml.bind.annotation.XmlType(name = "OtherErrorException", namespace = "org.xiajinsuo.epay.exception")
@org.apache.avro.specific.AvroGenerated
public class OtherErrorException extends io.bestpay.framework.base.CodeException {

    public OtherErrorException() {
        super();
        this.init();
    }

    public OtherErrorException(Object value, Throwable cause) {
        super(value, cause);
        this.init();
    }

    public OtherErrorException(Object msg) {
        super(msg);
        this.init();
    }

    public OtherErrorException(String msg) {
        super(msg);
        this.init(msg);
    }

    public OtherErrorException(Throwable cause) {
        super(cause);
        this.init();
    }

    private void init() {
        this.setErrCode("999999");
        this.setErrMsg("其他异常");
    }

    private void init(String msg) {
        this.setErrCode("999999");
        this.setErrMsg(msg);
    }
}