/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.bestpay.framework.api.protocol;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface BaseProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"BaseProtocol\",\"namespace\":\"io.bestpay.framework.api.protocol\",\"types\":[{\"type\":\"record\",\"name\":\"Page\",\"fields\":[{\"name\":\"page\",\"type\":\"int\",\"default\":1},{\"name\":\"pageSize\",\"type\":\"int\",\"default\":20},{\"name\":\"total\",\"type\":{\"type\":\"string\",\"java-class\":\"java.lang.Long\"},\"default\":0},{\"name\":\"data\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"java-class\":\"io.bestpay.framework.base.SpecificRecord\"}}}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends BaseProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = io.bestpay.framework.api.protocol.BaseProtocol.PROTOCOL;
  }
}