/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.bestpay.framework.api.protocol;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface DemoProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"DemoProtocol\",\"namespace\":\"io.bestpay.framework.api.protocol\",\"types\":[{\"type\":\"record\",\"name\":\"Page\",\"fields\":[{\"name\":\"page\",\"type\":\"int\",\"default\":1},{\"name\":\"pageSize\",\"type\":\"int\",\"default\":20},{\"name\":\"total\",\"type\":{\"type\":\"string\",\"java-class\":\"java.lang.Long\"},\"default\":0},{\"name\":\"data\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"java-class\":\"io.bestpay.framework.base.SpecificRecord\"}}}]}],\"messages\":{\"getProvinces\":{\"doc\":\"获取省份\",\"request\":[],\"response\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"java-class\":\"io.bestpay.framework.base.NameValue\"}}},\"create\":{\"doc\":\"创建对像\",\"request\":[{\"name\":\"entity\",\"type\":{\"type\":\"string\",\"java-class\":\"io.bestpay.framework.base.NameValue\"}}],\"response\":\"boolean\"},\"delete\":{\"doc\":\"通过id删除对像\",\"request\":[{\"name\":\"id\",\"type\":\"string\"}],\"response\":\"null\",\"one-way\":true},\"query\":{\"request\":[{\"name\":\"page\",\"type\":\"int\"},{\"name\":\"pageSize\",\"type\":\"int\"},{\"name\":\"params\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}],\"response\":\"Page\"}}}");
  /**
   * 获取省份
   */
  java.util.List<io.bestpay.framework.base.NameValue> getProvinces() throws org.apache.avro.AvroRemoteException;
  /**
   * 创建对像
   */
  boolean create(io.bestpay.framework.base.NameValue entity) throws org.apache.avro.AvroRemoteException;
  /**
   * 通过id删除对像
   */
  void delete(java.lang.CharSequence id);
  /**
   */
  io.bestpay.framework.api.protocol.Page query(int page, int pageSize, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> params) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends DemoProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = io.bestpay.framework.api.protocol.DemoProtocol.PROTOCOL;
    /**
     * 获取省份
     * @throws java.io.IOException The async call could not be completed.
     */
    void getProvinces(org.apache.avro.ipc.Callback<java.util.List<io.bestpay.framework.base.NameValue>> callback) throws java.io.IOException;
    /**
     * 创建对像
     * @throws java.io.IOException The async call could not be completed.
     */
    void create(io.bestpay.framework.base.NameValue entity, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void query(int page, int pageSize, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> params, org.apache.avro.ipc.Callback<io.bestpay.framework.api.protocol.Page> callback) throws java.io.IOException;
  }
}