/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.bestpay.framework.api.protocol;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface RegionProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"RegionProtocol\",\"namespace\":\"io.bestpay.framework.api.protocol\",\"types\":[],\"messages\":{\"getProvinces\":{\"doc\":\"获取省份\",\"request\":[],\"response\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"java-class\":\"io.bestpay.framework.base.NameValue\"}}},\"getCities\":{\"doc\":\"获取市级城市\",\"request\":[{\"name\":\"provinceCode\",\"type\":\"string\"}],\"response\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"java-class\":\"io.bestpay.framework.base.NameValue\"}}},\"getCounties\":{\"doc\":\"获取县/区\",\"request\":[{\"name\":\"cityCode\",\"type\":\"string\"}],\"response\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"java-class\":\"io.bestpay.framework.base.NameValue\"}}}}}");
  /**
   * 获取省份
   */
  java.util.List<io.bestpay.framework.base.NameValue> getProvinces() throws org.apache.avro.AvroRemoteException;
  /**
   * 获取市级城市
   */
  java.util.List<io.bestpay.framework.base.NameValue> getCities(java.lang.CharSequence provinceCode) throws org.apache.avro.AvroRemoteException;
  /**
   * 获取县/区
   */
  java.util.List<io.bestpay.framework.base.NameValue> getCounties(java.lang.CharSequence cityCode) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends RegionProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = io.bestpay.framework.api.protocol.RegionProtocol.PROTOCOL;
    /**
     * 获取省份
     * @throws java.io.IOException The async call could not be completed.
     */
    void getProvinces(org.apache.avro.ipc.Callback<java.util.List<io.bestpay.framework.base.NameValue>> callback) throws java.io.IOException;
    /**
     * 获取市级城市
     * @throws java.io.IOException The async call could not be completed.
     */
    void getCities(java.lang.CharSequence provinceCode, org.apache.avro.ipc.Callback<java.util.List<io.bestpay.framework.base.NameValue>> callback) throws java.io.IOException;
    /**
     * 获取县/区
     * @throws java.io.IOException The async call could not be completed.
     */
    void getCounties(java.lang.CharSequence cityCode, org.apache.avro.ipc.Callback<java.util.List<io.bestpay.framework.base.NameValue>> callback) throws java.io.IOException;
  }
}