/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

/**
 * @Copyright 2016 www.bestpay.io Inc. All rights reserved.
 */

package io.bestpay.sdk.base;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum SignType {
  HMAC, DES, RSA  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SignType\",\"namespace\":\"io.bestpay.sdk.base\",\"symbols\":[\"HMAC\",\"DES\",\"RSA\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /**   */
  public static SignType valueOf(int ordinal) {
	  SignType[] values = SignType.values();
	  for (SignType s : values) {
		  if (s.ordinal() == ordinal) {
			  return s;
		  }
	  }
	  throw new org.apache.avro.AvroRuntimeException("Bad ordinal");
  }  
}
