package com.alycloud.account.dto;

import com.test.model.MerchUserDTO;

public interface MerchUserDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merch_user
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merch_user
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    int insert(MerchUserDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merch_user
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    int insertSelective(MerchUserDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merch_user
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    MerchUserDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merch_user
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(MerchUserDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merch_user
     *
     * @mbggenerated Mon Oct 16 15:04:13 GMT+08:00 2017
     */
    int updateByPrimaryKey(MerchUserDTO record);
}