/**
 * Autogenerated by bestpay-maven-plugin
 * DO NOT EDIT DIRECTLY
 *
 * @Copyright 2016 www.bestpay.io Inc. All rights reserved.
 *
 */

/**
 * @Copyright 2016 www.bestpay.io Inc. All rights reserved.
 */

package io.bestpay.framework.exception;

@SuppressWarnings("all")
@javax.xml.bind.annotation.XmlRootElement
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
@javax.xml.bind.annotation.XmlType(name="NotSupportServiceException", namespace="io.bestpay.framework.exception")
@org.apache.avro.specific.AvroGenerated
public class NotSupportServiceException extends io.bestpay.framework.base.CodeException {

	public NotSupportServiceException() {
		super();
		this.init();
	}

	public NotSupportServiceException(Object value, Throwable cause) {
		super(value, cause);
		this.init();
	}

	public NotSupportServiceException(Object value) {
		super(value);
		this.init();
	}

	public NotSupportServiceException(Throwable cause) {
		super(cause);
		this.init();
	}

	private void init() {
		this.setErrCode("000206");
		this.setErrMsg("不支持的服务");
	}
}